name: Test and Email Results

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: githubActions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pdo_pgsql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up environment variables
        run: |
          echo "APP_ENV=testing" > .env
          echo "APP_KEY=$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=githubActions" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        id: run-tests
        run: php artisan test

      - name: Send email with test results
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.resend.com
          server_port: 587
          username: "resend"
          password: "re_TSxQ6DgW_NDfipc6UZwAGygXruDA8Hgmw"  # Your Resend API key
          subject: "Test Results for ${{ github.repository }}"
          body: |
            Test results for commit ${{ github.sha }}:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref }}
            - Status: ${{ job.status }}
            - Test Output:
              ${{ steps.run-tests.outputs.result }}
          to: echchablihamza1@gmail.com
          from: "none.example.com"  # Use a verified sender domain from Resend
