name: Test and Deploy

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: githubActions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pdo_pgsql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up environment variables
        run: |
          echo "APP_ENV=testing" > .env
          echo "APP_KEY=$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=githubActions" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

  deploy:
    needs: test  # This job depends on the 'test' job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SSH_PRIVATE_KEY }} \
              user@your-server-ip \
              "cd /var/www/your-app && git fetch origin main && git reset --hard origin/main && composer install --no-dev && php artisan migrate --force"